config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"
  resources :teams, only: [:index, :new, :create]
  resources :players, only: [:index, :new, :create]
  resources :games, only: [:index, :show, :new, :create] do
    resources :performances, only: [:index, :new, :create]
  end
  # :update do
  #   resources :performances, only: [:new, :create]
  # end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :home_team, class_name: 'Team'
  belongs_to :away_team, class_name: 'Team'
  has_many :performances
  has_many :players, through: :performances
  accepts_nested_attributes_for :performances

  def score(team)
    player_performances = performances.filter { |performance| performance.player.team == team }
    player_performances.sum(&:points)
  end

  def winner
    if score(home_team) > score(away_team)
      home_team
    else
      away_team
    end
  end

  def loser
    if score(home_team) < score(away_team)
      home_team
    else
      away_team
    end
  end

  def best_performance
    performances.order(points: :desc).first
  end
end

app/models/performance.rb
class Performance < ApplicationRecord
  belongs_to :game 
  belongs_to :player
  validates :points, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :assists, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :rebounds, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :team
  has_many :performances
  has_many :games, through: :performances
  validates :name, presence: true, uniqueness: true

  def per_game_stats(stat)
    (performances.sum(&stat).to_f / performances.count).round(2)
  end
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :user
  has_many :games
  has_many :players
  has_many :performances, through: :players
  accepts_nested_attributes_for :players
  validates :name, presence: true, uniqueness: true
  validates :slogan, presence: true
  validates :image_url, presence: true
  scope :except_team_of, ->(user) { where.not(id: user.team.id )}
  ##Try more scope methods ^^^

  def wins
    Game.all.filter { |game| game.winner == self}.count
  end

  def losses
    Game.all.filter { |game| game.loser == self}.count
  end

  def record
    "( #{wins} - #{losses} )"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one :team
  has_many :players, through: :team
  attr_accessor :login
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  ## Add username column to user table

  # <div class="field">
  #   <%= f.label :name %><br />
  #   <%= f.text_field :name, autofocus: true %>
  # </div>
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def current_team
    current_user.team
  end

  def current_players
    current_team.players
  end

  private

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,
        keys: [:username, :email, :password, :password_confirmation])
      devise_parameter_sanitizer.permit(:sign_in,
        keys: [:login, :password, :password_confirmation])
      devise_parameter_sanitizer.permit(:account_update,
        keys: [:username, :email, :password_confirmation, :current_password])
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
    @home_player1 = @game.home_team.players.first
    @hp1_form = @game.performances.build(player: @home_player1)

    @home_player2 = @game.home_team.players.second
    @hp2_form = @game.performances.build(player: @home_player2)

    @away_player1 = @game.away_team.players.first
    @ap1_form = @game.performances.build(player: @away_player1)

    @away_player2 = @game.away_team.players.second
    @ap2_form = @game.performances.build(player: @away_player2)
    ## Better variable names
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      redirect_to game_path(@game)
    else
      render :new
    end
  end

  private

  def game_params
    params.require(:game).permit(:home_team_id, :away_team_id, performances_attributes: [:game_id, :player_id, :points])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/performances_controller.rb
class PerformancesController < ApplicationController
  def create
    errors = []
    performances_hash.each do |per|
      performance = Performance.new(per.permit(:game_id, :player_id, :points, :assists, :rebounds))
      errors << "Failed to save stats!" unless performance.save
    end
    redirect_to root_path if errors.empty?
  end

  def performances_hash
    params.require(:performances)
  end

  def permitted_performance_params(params)

  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @players = Player.all
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  def index
    @teams = Team.all.filter { |team| team.players.any? }
  end

  def show

  end

  def new 
    @team = Team.new
    2.times { @team.players.build }
  end

  def create
    @team = Team.new(team_params)
    if @team.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  # def player_params
  #   params.require(:player).permit(:team_id, :name, :position)
  # end

  def team_params
    params.require(:team).permit(:user_id, :name, :slogan, :image_url, players_attributes: [:team_id, :name, :position])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/games/index.html.erb
<ul>
<% @games.each do |game| %>
  <li><%= game.home_team.name %> ( <%= game.score(game.home_team) %> ) vs. ( <%= game.score(game.away_team) %> ) <%= game.away_team.name  %></li>
  <p>Player of the Game: <%= game.best_performance.player.name %> ( <%= game.best_performance.points %> points )</p><br>
<% end %>
</ul>

app/views/games/new.html.erb
<div class="d-flex justify-content-center m-5">
  <h1>New Game</h1>
</div>
<div class="d-flex justify-content-center fs-3">
  <div class="d-flex w-25 justify-content-center border rounded p-3">
    <%= form_for @game do |f| %>
      <div class="row">
        <div class="col">
          <%= f.hidden_field :home_team_id, value: current_user.team.id %>
          <label class="badge bg-primary mb-2">Home Team</label><br>
          <%= current_user.team.name %><br>
          <br>
        </div>
        <div class="col">
          <label class="badge bg-black mb-2">Away Team</label><br>
          <%= f.collection_select :away_team_id, Team.except_team_of(current_user), :id, :name %><br>
          <br>
        </div>
      </div>
      <div class="row">
       <%= f.submit "Start" %>
      </div>
    <% end %>
  </div>
</div>

app/views/games/show.html.erb
<div class="d-flex justify-content-center m-5">
  <h1><%= @game.home_team.name %> vs. <%= @game.away_team.name %>
</div>
<div class="d-flex justify-content-center">
  <%= form_tag("/games/#{@game.id}/performances") do %>
    <%= fields_for "performances[]", @hp1_form do |ff| %>
      <label><%= @home_player1.name %>:</label><br>
      <%= ff.hidden_field :player_id, value: @home_player1.id %>
      <%= ff.hidden_field :game_id, value: @game.id %>
      <%= ff.number_field :points, placeholder: "Points" %><br>
      <%= ff.number_field :assists, placeholder: "Assists"  %><br>
      <%= ff.number_field :rebounds, placeholder: "Rebounds" %><br>
    <% end %>
    <br>
    <%= fields_for "performances[]", @hp2_form do |ff| %>
      <label><%= @home_player2.name %>:</label><br>
      <%= ff.hidden_field :player_id, value: @home_player2.id %>
      <%= ff.hidden_field :game_id, value: @game.id %>
      <%= ff.number_field :points, placeholder: "Points" %><br>
      <%= ff.number_field :assists, placeholder: "Assists"  %><br>
      <%= ff.number_field :rebounds, placeholder: "Rebounds" %><br>
    <% end %>
    <br>
    <%= fields_for "performances[]", @ap1_form do |ff| %>
      <label><%= @away_player1.name %>:</label><br>
      <%= ff.hidden_field :player_id, value: @away_player1.id %>
      <%= ff.hidden_field :game_id, value: @game.id %>
      <%= ff.number_field :points, placeholder: "Points"%><br>
      <%= ff.number_field :assists, placeholder: "Assists" %><br>
      <%= ff.number_field :rebounds, placeholder: "Rebounds" %><br>
    <% end %>
    <br>
    <%= fields_for "performances[]", @ap2_form do |ff| %>
      <label><%= @away_player2.name %>:</label><br>
      <%= ff.hidden_field :player_id, value: @away_player2.id %>
      <%= ff.hidden_field :game_id, value: @game.id %>
      <%= ff.number_field :points, placeholder: "Points" %><br>
      <%= ff.number_field :assists, placeholder: "Assists"  %><br>
      <%= ff.number_field :rebounds, placeholder: "Rebounds" %><br>
    <% end %>

    <%= submit_tag "Finish Game" %>
  <% end %>
</div>

app/views/home/index.html.erb
<% unless user_signed_in? %>
  <h1>Welcome coach!</h1>
<% else %>
  <div class="container-fluid border border-3 bg-primary">
    <div class="row mx-5 my-4 d-flex bd-highlight align-items-center">
      <% if current_user.team.blank? %>
        <div class="col bd-highlight flex-fill">
          <p class="fs-2 text-light">Welcome to Hoop Heroes! Build your 2v2 squad so you can log their games and keep track of your players' stats...</p>
        </div>
        <div class="col bd-highlight">
          <%= button_to "New Team +", new_team_path, method: :get, class: 'btn btn-light btn-outline-success' %>
        </div>
      <% else %>
        <div class="col">
          <h1><%= current_user.team.name %></h1>
        </div>
        <% current_user.team.players.each do |player| %>
          <p class="col fs-2"><span class="badge bg-white text-black"><%= player.position %></span> <%= player.name %></p>
        <% end %>
        <div class="col">
          <%= button_to "Record New Game", new_game_path, method: :get, class: 'btn btn-light btn-outline-success' %>
        </div>
    </div>
  </div>
  <div class="d-flex m-3 justify-content-center">
    <h1>Recent Matchups:</h1>
  </div>
    <div class="d-flex flex-wrap justify-content-around my-5">
    <% Game.where(home_team_id: current_user.team.id).or(Game.where(away_team_id: current_user.team.id)).each do |game| %>
      <div class="card fs-3 d-flex align-items-center shadow p-3 mb-5 bg-body rounded" style="width: 25rem;">
          <div class="card-body">
            <p class="card-title badge bg-dark"><%= game.home_team.name %> <span class="badge bg-primary fs-6">VS.</span> <%= game.away_team.name %> 
            <% if game.winner == current_user.team %>
              <span class="badge bg-success fs-5">W</span>
            <% else %>
              <span class="badge bg-danger fs-5">L</span>
            <% end %>
            </p>
            <ul class="list-group list-group-flush">
            <% game.performances.each do |per| %>
              <li class="list-group-item"><strong class=<%= "text-primary" if per.player.team == current_user.team %>><%= per.player.name %></strong> - ( <%= per.points %> / <%= per.assists %> / <%= per.rebounds %> )</li>
            <% end %>
            </ul>
          </div>
      </div>
    <% end %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HoopHeroes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <% if notice %>
      <div class="notice alert-primary alert-dismissable p-2">
        <%= notice %>
      </div>
    <% end %>
    <% if alert %>
      <p class="alert-primary"><%= alert %></p>
    <% end %>
    <% if user_signed_in? %>
      <%= render 'shared/user_navbar' %>
    <% else %>
      <%= render 'shared/home_navbar' %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/players/index.html.erb
<table class="table table-striped fs-4">
  <thead>
   <tr>
      <th scope="col">Player</th>
      <th scope="col">PPG</th>
      <th scope="col">APG</th>
      <th scope="col">RPG</th>
    </tr>
  </thead>
  <tbody>
  <% @players.each do |player| %>
    <tr>
      <td>
        <img style="height: 4rem;" src="https://th.bing.com/th/id/R.ca11ff5110bfb2b316716f065a0236ac?rik=JCF6rzE8UvBAVg&riu=http%3a%2f%2fsynergysportsfacility.com%2fwp-content%2fuploads%2f2015%2f02%2fblank-profile.jpg&ehk=eech4HE2vO6ItG1ANhJVHCvGVTwcb4kASKRneNkYu5k%3d&risl=&pid=ImgRaw&r=0"> 
        <strong class=<%= "text-primary" if player.team == current_user.team %>><%= player.name %></strong> - [ <%= player.position %> ] - <%= player.team.name %>
      </td>
      <td><%= player.per_game_stats(:points) %></td>
      <td><%= player.per_game_stats(:assists) %></td>
      <td><%= player.per_game_stats(:rebounds) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/shared/_home_navbar.html.erb
<ul class="nav justify-content-end">
  <li class="nav-item">
    <%= link_to 'Log In', new_user_session_path, class: 'nav-link' %>
  </li>
  <li class="nav-item">
    <%= link_to 'Sign Up Here', new_user_registration_path, class: 'nav-link' %>
  </li>
</ul>

app/views/shared/_user_navbar.html.erb
<ul class="nav nav-pills nav-fill">
  <h1 class="navbar-brand fst-italic">HOOP HEROES <img src="https://ae01.alicdn.com/kf/HTB1iTUKKlLoK1RjSZFuq6xn0XXaH/Mini-Yellow-Basketball-Rubber-Training-Small-Size-for-Indoor-Mini-Basketball.jpg" height="40px"></h1>
  <div class="vr"></div>
  <li class="nav-item">
    <a class="nav-link" aria-current="page" href="/">MyTEAM</a>
  </li>
  <div class="vr"></div>
  <li class="nav-item">
    <a class="nav-link" aria-current="page" href="/teams">Squads</a>
  </li>
  <div class="vr"></div>
  <li class="nav-item">
    <a class="nav-link" aria-current="page" href="/players">Hoopers</a>
  </li>
  <div class="vr"></div>
  <li class="nav-item">
    <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
  </li>
</ul>